
/*
 *	MCreator note: This file will be REGENERATED on each build.
 */
package com.yixi_xun.more_potion_effects.init;

import com.yixi_xun.more_potion_effects.MorePotionEffectsMod;
import com.yixi_xun.more_potion_effects.mob_effects.*;
import net.minecraft.core.registries.BuiltInRegistries;
import net.minecraft.world.effect.MobEffect;
import net.neoforged.neoforge.registries.DeferredHolder;
import net.neoforged.neoforge.registries.DeferredRegister;

public class MorePotionEffectsModMobEffects {
	public static final DeferredRegister<MobEffect> REGISTRY = DeferredRegister.create(BuiltInRegistries.MOB_EFFECT, MorePotionEffectsMod.MOD_ID);
	public static final DeferredHolder<MobEffect, MobEffect> IMMUNE = REGISTRY.register("immune", ImmuneMobEffect::new);
	public static final DeferredHolder<MobEffect, MobEffect> STRONG_HEART = REGISTRY.register("strong_heart", StrongHeartMobEffect::new);
	public static final DeferredHolder<MobEffect, MobEffect> EFFECT_SIPHON = REGISTRY.register("effect_siphon", EffectSiphonMobEffect::new);
	public static final DeferredHolder<MobEffect, MobEffect> LOCK = REGISTRY.register("lock", LockMobEffect::new);
	public static final DeferredHolder<MobEffect, MobEffect> RANDOM_EFFECT = REGISTRY.register("random_effect", RandomEffectMobEffect::new);
	public static final DeferredHolder<MobEffect, MobEffect> RANDOM_NEGATIVE_EFFECT = REGISTRY.register("random_negative_effect", RandomNegativeEffectMobEffect::new);
	public static final DeferredHolder<MobEffect, MobEffect> RANDOM_POSITIVE_EFFECT = REGISTRY.register("random_positive_effect", RandomPositiveEffectMobEffect::new);
	public static final DeferredHolder<MobEffect, MobEffect> REUSE = REGISTRY.register("reuse", ReuseMobEffect::new);
	public static final DeferredHolder<MobEffect, MobEffect> IMPRISON = REGISTRY.register("imprison", ImprisonMobEffect::new);
	public static final DeferredHolder<MobEffect, MobEffect> IMMORTAL = REGISTRY.register("immortal", ImmortalMobEffect::new);
	public static final DeferredHolder<MobEffect, MobEffect> CLIMBING = REGISTRY.register("climbing", ClimbingMobEffect::new);
	public static final DeferredHolder<MobEffect, MobEffect> ATTACK_AOE = REGISTRY.register("attack_aoe", AttackAoeMobEffect::new);
	public static final DeferredHolder<MobEffect, MobEffect> ADAPTATION = REGISTRY.register("adaptation", AdaptationMobEffect::new);
	public static final DeferredHolder<MobEffect, MobEffect> TRUE_DAMAGE = REGISTRY.register("true_damage", TrueDamageMobEffect::new);
	public static final DeferredHolder<MobEffect, MobEffect> STATIC_LIFE = REGISTRY.register("static_life", StaticLifeMobEffect::new);
	public static final DeferredHolder<MobEffect, MobEffect> AGGRO = REGISTRY.register("aggro", AggroMobEffect::new);
	public static final DeferredHolder<MobEffect, MobEffect> DECAY = REGISTRY.register("decay", DecayMobEffect::new);
	public static final DeferredHolder<MobEffect, MobEffect> EXTENSION = REGISTRY.register("extension", ExtensionMobEffect::new);
	public static final DeferredHolder<MobEffect, MobEffect> SHATTERED_HEART = REGISTRY.register("shattered_heart", ShatteredHeartMobEffect::new);
	public static final DeferredHolder<MobEffect, MobEffect> INJURY_LINK = REGISTRY.register("injury_link", InjuryLinkMobEffect::new);
	public static final DeferredHolder<MobEffect, MobEffect> SIDE_EFFECT = REGISTRY.register("side_effect", SideEffectMobEffect::new);
	public static final DeferredHolder<MobEffect, MobEffect> UNYIELDING_WILLPOWER = REGISTRY.register("unyielding_willpower", UnyieldingWillpowerMobEffect::new);
	public static final DeferredHolder<MobEffect, MobEffect> STASIS_FIELD = REGISTRY.register("stasis_field", StasisFieldMobEffect::new);
	public static final DeferredHolder<MobEffect, MobEffect> DISPEL = REGISTRY.register("dispel", DispelMobEffect::new);
	public static final DeferredHolder<MobEffect, MobEffect> GLUTTONY = REGISTRY.register("gluttony", GluttonyMobEffect::new);
	public static final DeferredHolder<MobEffect, MobEffect> RECOIL = REGISTRY.register("recoil", RecoilMobEffect::new);
	public static final DeferredHolder<MobEffect, MobEffect> VIRUS = REGISTRY.register("virus", VirusMobEffect::new);
	public static final DeferredHolder<MobEffect, MobEffect> DEATH = REGISTRY.register("death", DeathMobEffect::new);
	public static final DeferredHolder<MobEffect, MobEffect> RANK = REGISTRY.register("rank", RankMobEffect::new);
	public static final DeferredHolder<MobEffect, MobEffect> CONFUSION = REGISTRY.register("confusion", ConfusionMobEffect::new);
	public static final DeferredHolder<MobEffect, MobEffect> CORROSION = REGISTRY.register("corrosion", CorrosionMobEffect::new);
	public static final DeferredHolder<MobEffect, MobEffect> FEAR = REGISTRY.register("fear", FearMobEffect::new);
	public static final DeferredHolder<MobEffect, MobEffect> GILLS = REGISTRY.register("gills", GillsMobEffect::new);
	public static final DeferredHolder<MobEffect, MobEffect> INJURY_ACCUMULATION = REGISTRY.register("injury_accumulation", InjuryAccumulationMobEffect::new);
	public static final DeferredHolder<MobEffect, MobEffect> SELF_HEALING = REGISTRY.register("self_healing", SelfHealingMobEffect::new);
	public static final DeferredHolder<MobEffect, MobEffect> CALMING = REGISTRY.register("calming", CalmingMobEffect::new);
	public static final DeferredHolder<MobEffect, MobEffect> UPGRADE = REGISTRY.register("upgrade", UpgradeMobEffect::new);
	public static final DeferredHolder<MobEffect, MobEffect> BLEEDING_IMMUNITY = REGISTRY.register("bleeding_immunity", BleedingImmunityMobEffect::new);
	public static final DeferredHolder<MobEffect, MobEffect> POTION_ANTAGONISM = REGISTRY.register("potion_antagonism", PotionAntagonismMobEffect::new);
	public static final DeferredHolder<MobEffect, MobEffect> KINETIC = REGISTRY.register("kinetic", KineticMobEffect::new);
	public static final DeferredHolder<MobEffect, MobEffect> HEALTH_CONVERSION = REGISTRY.register("health_conversion", HealthConversionMobEffect::new);
	public static final DeferredHolder<MobEffect, MobEffect> RESONATING_STRIKE = REGISTRY.register("resonating_strike", ResonatingStrikeMobEffect::new);
	public static final DeferredHolder<MobEffect, MobEffect> PIERCE = REGISTRY.register("pierce", PierceMobEffect::new);
	public static final DeferredHolder<MobEffect, MobEffect> MELEE_DOMAIN = REGISTRY.register("melee_domain", MeleeDomainMobEffect::new);
	public static final DeferredHolder<MobEffect, MobEffect> QUICK_DRAW = REGISTRY.register("quick_draw", QuickDrawMobEffect::new);
	public static final DeferredHolder<MobEffect, MobEffect> ENHANCE_DIGGING = REGISTRY.register("enhance_digging", EnhanceDiggingMobEffect::new);
	public static final DeferredHolder<MobEffect, MobEffect> SLOT_LOCK = REGISTRY.register("slot_lock", SlotLockMobEffect::new);
	public static final DeferredHolder<MobEffect, MobEffect> FEAST = REGISTRY.register("feast", FeastMobEffect::new);
	public static final DeferredHolder<MobEffect, MobEffect> HOMING = REGISTRY.register("homing", HomingMobEffect::new);
	public static final DeferredHolder<MobEffect, MobEffect> COMPANION = REGISTRY.register("companion", CompanionMobEffect::new);
	public static final DeferredHolder<MobEffect, MobEffect> FIRM = REGISTRY.register("firm", FirmMobEffect::new);
	public static final DeferredHolder<MobEffect, MobEffect> TOUCH = REGISTRY.register("touch", TouchMobEffect::new);
	public static final DeferredHolder<MobEffect, MobEffect> WEAKENING_RECOVERY = REGISTRY.register("weakening_recovery", WeakeningRecoveryMobEffect::new);
	public static final DeferredHolder<MobEffect, MobEffect> HUGE_FORCE = REGISTRY.register("huge_force", HugeForceMobEffect::new);
	public static final DeferredHolder<MobEffect, MobEffect> FRAGILE = REGISTRY.register("fragile", FragileMobEffect::new);
	public static final DeferredHolder<MobEffect, MobEffect> REPAIR = REGISTRY.register("repair", RepairMobEffect::new);
	public static final DeferredHolder<MobEffect, MobEffect> ARMOR_BROKEN = REGISTRY.register("armor_broken", ArmorBrokenMobEffect::new);
	public static final DeferredHolder<MobEffect, MobEffect> FLIGHT = REGISTRY.register("flight", FlightMobEffect::new);
	public static final DeferredHolder<MobEffect, MobEffect> SUFFOCATION = REGISTRY.register("suffocation", SuffocationMobEffect::new);
	public static final DeferredHolder<MobEffect, MobEffect> LEECHING = REGISTRY.register("leeching", LeechingMobEffect::new);
	public static final DeferredHolder<MobEffect, MobEffect> MORE_RANGE = REGISTRY.register("more_range", MoreRangeMobEffect::new);
	public static final DeferredHolder<MobEffect, MobEffect> HEALTH_SACRIFICE = REGISTRY.register("health_sacrifice", HealthSacrificeMobEffect::new);
	public static final DeferredHolder<MobEffect, MobEffect> BLEEDING = REGISTRY.register("bleeding", BleedingMobEffect::new);
	public static final DeferredHolder<MobEffect, MobEffect> LIGHTLY_LOADED = REGISTRY.register("lightly_loaded", LightlyLoadedMobEffect::new);
	public static final DeferredHolder<MobEffect, MobEffect> HEAVY_ARMOR = REGISTRY.register("heavy_armor", HeavyArmorMobEffect::new);
	public static final DeferredHolder<MobEffect, MobEffect> HEAVY = REGISTRY.register("heavy", HeavyMobEffect::new);
	public static final DeferredHolder<MobEffect, MobEffect> HIGHLY_TOXIC = REGISTRY.register("highly_toxic", HighlyToxicMobEffect::new);
	public static final DeferredHolder<MobEffect, MobEffect> INJURY_OUTBURST = REGISTRY.register("injury_outburst", InjuryOutburstMobEffect::new);
	public static final DeferredHolder<MobEffect, MobEffect> ACCURATE = REGISTRY.register("accurate", AccurateMobEffect::new);
	public static final DeferredHolder<MobEffect, MobEffect> MISALIGNMENT = REGISTRY.register("misalignment", MisalignmentMobEffect::new);
	public static final DeferredHolder<MobEffect, MobEffect> PERCENTAGE_RECOVERY = REGISTRY.register("percentage_recovery", PercentageRecoveryMobEffect::new);
	public static final DeferredHolder<MobEffect, MobEffect> STEP_UP = REGISTRY.register("step_up", StepUpMobEffect::new);
	public static final DeferredHolder<MobEffect, MobEffect> EVASION = REGISTRY.register("evasion", EvasionMobEffect::new);
	public static final DeferredHolder<MobEffect, MobEffect> INJURY_LIMITATION = REGISTRY.register("injury_limitation", InjuryLimitationMobEffect::new);
	public static final DeferredHolder<MobEffect, MobEffect> SLAUGHTER = REGISTRY.register("slaughter", SlaughterMobEffect::new);
	public static final DeferredHolder<MobEffect, MobEffect> SOLID_SHIELD = REGISTRY.register("solid_shield", SolidShieldMobEffect::new);
	public static final DeferredHolder<MobEffect, MobEffect> CURSE = REGISTRY.register("curse", CurseMobEffect::new);
	public static final DeferredHolder<MobEffect, MobEffect> MAGIC_SHIELD = REGISTRY.register("magic_shield", MagicShieldMobEffect::new);
	public static final DeferredHolder<MobEffect, MobEffect> BROKEN_MAGIC_SHIELD = REGISTRY.register("broken_magic_shield", BrokenMagicShieldMobEffect::new);
	public static final DeferredHolder<MobEffect, MobEffect> MAGIC_FOCUS = REGISTRY.register("magic_focus", MagicFocusMobEffect::new);
	public static final DeferredHolder<MobEffect, MobEffect> MAGIC_INHIBITION = REGISTRY.register("magic_inhibition", MagicInhibitionMobEffect::new);
	public static final DeferredHolder<MobEffect, MobEffect> GAMBLER = REGISTRY.register("gambler", GamblerMobEffect::new);
	public static final DeferredHolder<MobEffect, MobEffect> FAST_ATTACK = REGISTRY.register("fast_attack", FastAttackMobEffect::new);
	public static final DeferredHolder<MobEffect, MobEffect> LIFE_DEBT = REGISTRY.register("life_debt", LifeDebtMobEffect::new);
	public static final DeferredHolder<MobEffect, MobEffect> COMBUSTION = REGISTRY.register("combustion", CombustionMobEffect::new);
	public static final DeferredHolder<MobEffect, MobEffect> AIRSTRIDE = REGISTRY.register("airstride", AirstrideMobEffect::new);
	public static final DeferredHolder<MobEffect, MobEffect> WANE = REGISTRY.register("wane", WaneMobEffect::new);
	public static final DeferredHolder<MobEffect, MobEffect> ERUDITE = REGISTRY.register("erudite", EruditeMobEffect::new);
	public static final DeferredHolder<MobEffect, MobEffect> DEFLAGRATION = REGISTRY.register("deflagration", DeflagrationMobEffect::new);
	public static final DeferredHolder<MobEffect, MobEffect> VEILED_PRESENCE = REGISTRY.register("veiled_presence", VeiledPresenceMobEffect::new);
	public static final DeferredHolder<MobEffect, MobEffect> SPATIAL_ANCHOR = REGISTRY.register("spatial_anchor", SpatialAnchorMobEffect::new);
	public static final DeferredHolder<MobEffect, MobEffect> ASYLUM = REGISTRY.register("asylum", AsylumMobEffect::new);
	public static final DeferredHolder<MobEffect, MobEffect> OVERDOSE_TREATMENT = REGISTRY.register("overdose_treatment", OverdoseTreatmentMobEffect::new);
}
